name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-venv openjdk-17-jdk git zip unzip
        pip3 install buildozer cython==0.29.19
        
    - name: Setup Android SDK and accept licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools
        mv tools cmdline-tools/latest
        export ANDROID_HOME=$PWD
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
        
    - name: Build APK
      run: |
        buildozer -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
